### ISSUE TITLE
Copyright year

### ISSUE THREAD

**Issue by ugeorge** [forsyde/forsyde-web-theme#1]
I believe there should be an automatic means to update the copyright year in the ForSyDe pages footer with every push. Right now it is hard-coded in every page, e.g. "©2018-2019". Should be something along the lines of `©2018-{{ thisyear  }}`.

**Comment by ugeorge** [comment]
Maybe a "last updated" entry in the footer would help with citing material in the web pages...

**Comment by Rojods** [comment]
Fixed with a commit that is included in version `0.1.3`.
